packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - '@hookform/resolvers@5.7.0'
